version: '3.8'
services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "9000:9000"  # Exponer el backend en el puerto 9000
    networks:
      - app-network
    environment:
      SPRING_DATA_MONGODB_URI: mongodb+srv://ftfernandez:dufc9Mrptf9zEiQS@ing-soft-tp-grupal.4w2qt.mongodb.net/newdb?retryWrites=true&w=majority
    depends_on:
      - frontend

  frontend:
    build:
      context: .
      dockerfile: client/Dockerfile
    ports:
      - "3000:3000"  # Exponer el frontend en el puerto 3000
    networks:
      - app-network

networks:
  app-network:
    driver: bridge